### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by pskrunner14** [pskrunner14/lstm-from-scratch#1]
TO-DO:
- [x] Write abstract class for `LSTM Cell`.
- [x] Implement the `LSTM Cell`.
- [x] Modify implementation to accommodate multiple `LSTM` layers.
- [x] Implement a `Dense` layer.
- [x] Implement an `Embedding` layer.
- [ ] Implement backprop for all layers.
- [ ] Implement `NLL` loss or `Perplexity`.
- [ ] Use `Adam` and `SGD` for weight updates during backpropagation.
- [x] Add utility functions for reading files for training and testing data.
- [ ] Add a `Trainer` class for training of the model.
- [ ] Show working model on an example task.
